# Generated by Django 5.2.14 on 2026-05-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name': 'Étudiant'},
        ),
    ]
